
spring.application.name=ExamenAPI

server.port=8081


spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}


spring.data.mongodb.database=examen_db